spring:
  application:
    name: myclient

eureka:
  instance:
#  本服务10s内没有心跳,就将该服务从服务端剔除
    lease-expiration-duration-in-seconds: 10
#    每隔5s心跳一次,证明本服务还活着
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,,http://localhost:8762/eureka/
